# Use NEXT_PATCH_VERSION instead of RESOLVED_VERSION for now, until 1.0.0 is reached
name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
categories:
- title: '⚡ Breaking changes'
  label: 'breaking'
- title: '🚀 New features'
  label: 'feature'
- title: '🐛 Bug fixes'
  label: 'bugfix'
- title: '🔧 Maintenance'
  label: 'maintenance'
change-template: '* #$NUMBER $TITLE @$AUTHOR'
version-resolver:
  major:
    labels:
    - 'breaking'
  minor:
    labels:
    - 'feature'
  patch:
    labels:
    - 'bugfix'
    - 'maintenance'
  default: patch
template: |
  $CHANGES
replacers:
# Make headings smaller
- search: '/##/g'
  replace: '####'