# This file generates an Xcode project used to easily run scripts

name: BuildSystemGenerator
fileGroups: [project.yml, .sourcery.yml]

aggregateTargets:
  sourcery:
    buildScripts:
      - name: Sourcery
        script: |
          sourcery

  xcodegen:
    buildScripts:
      - name: Xcodegen
        script: |
          rm -rf *.xcodeproj && xcodegen

  carthage:
    buildScripts:
      - name: Carthage
        script: |
          carthage bootstrap --no-use-binaries --platform iOS
