name: "taskfile"
mode: "root"
content: |
  #!/bin/zsh
  ¶
  #####################################################################
  # This file contains several functions that can be run as tasks
  #
  # In order to run them easily, do:
  # > source {{global.fileName}}
  #
  # After sourcing the script you can run each task by its name, for example:
  # > help
  #####################################################################
  ¶
  # Fail if exit code is not zero, in pipes, and also if variable is not set
  # See: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
  set -euo pipefail
  ¶
  function setup() {
    echo "✨ Install project dependencies"
    mint install yonaskolb/XcodeGen@{{custom.xcodeGenVersion}}
    gem install cocoapods -v {{custom.cocoapodsVersion}}
    gem install cocoapods-binary -v {{custom.cocoapodsBinaryVersion}}
  ¶
    echo "✨ Setup project"
    pod install
    xcodegen
  }
  ¶
  function test() {
    xcodebuild test -project All.xcodeproj -scheme All -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest'
  }
  ¶
  function help() {
    echo -n "The available tasks are: "
    # Approach inspired by https://stackoverflow.com/a/2641911
    grep "^function" {{global.fileName}} | sed -e 's/function //g' | sed -e 's/() {//g' | xargs | sed -e 's/ /, /g'
  }
