name: All

options:
  xcodeGenVersion: {{global.xcodeGenVersion}}

projectReferences:
  Pods:
    path: Pods/Pods.xcodeproj
{% for module in modules where module.kind == "firstParty" %}
  {{module.name}}:
    {% if "App" in module.name %}
    path: {{module.path}}/{{module.name}}.xcodeproj
    {% else %}
    path: Pods/{{module.name}}.xcodeproj
    {% endif %}
{% endfor %}

schemes:
  All:
    build:
      targets:
        {% for module in modules where module.kind == "firstParty" %}
        {% if "App" in module.name %}
        {{module.name}}/{{module.name}}Tests: all
        {% else %}
        {{module.name}}/{{module.name}}-Unit-Tests: all
        {% endif %}
        {% endfor %}
    test:
      gatherCoverageData: true
      targets:
      {% for module in modules where module.kind == "firstParty" %}
      {% if "App" in module.name %}
      - name: {{module.name}}/{{module.name}}Tests
      {% else %}
      - name: {{module.name}}/{{module.name}}-Unit-Tests
      {% endif %}
        randomExecutionOrder: true
      {% endfor %}
