name: All

options:
  xcodeGenVersion: <%= global.xcodeGenVersion %>

projectReferences:
<%_ for module in modules.firstParty { -%>
  <%= module.name %>:
    path: <%= module.path.relative(to: env.output.parent) %>/<%= module.name %>.xcodeproj
<%_ } -%>

schemes:
  All:
    build:
      targets:
        <%_ for module in modules.firstParty { -%>
        <%= module.name %>/<%= module.name %>Tests: all
        <%_ } -%>
    test:
      gatherCoverageData: true
      targets:
      <%_ for module in modules.firstParty { -%>
        - name: <%= module.name %>/<%= module.name %>Tests
          randomExecutionOrder: true
      <%_ } -%>
