name: All

options:
  xcodeGenVersion: {{global.xcodeGenVersion}}

projectReferences:
{% for module in modules where module.kind == "firstParty" %}
  {{module.name}}:
    path: {{module.location.path}}/{{module.name}}.xcodeproj
{% endfor %}

schemes:
  All:
    build:
      targets:
        {% for module in modules where module.kind == "firstParty" %}
        {{module.name}}/{{module.name}}Tests: all
        {% endfor %}
    test:
      gatherCoverageData: true
      targets:
      {% for module in modules where module.kind == "firstParty" %}
        - name: {{module.name}}/{{module.name}}Tests
          randomExecutionOrder: true
      {% endfor %}
