name: CI-master
on:
  push:
    branches: ['master']

jobs:
  remove_release_draft:
    runs-on: ubuntu-latest
    steps:
    # Removing the previously created draft release is a workaround for the fact that
    # actions/upload-release-asset does not support overriding the existing release
    # asset. See: https://github.com/actions/upload-release-asset/pull/22
    - uses: hugo19941994/delete-draft-releases@v0.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: [remove_release_draft]
    runs-on: macos-10.15
    name: test - Xcode ${{ matrix.xcode }}
    strategy:
      matrix:
        xcode: 
        - 11.4.1
        - 11.5
        - 11.7
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app
    steps:
    - uses: actions/checkout@v2
    - run: ./taskfile selectXcode
    - run: ./taskfile setup
    - run: ./taskfile checkLinks ${{ github.sha }}
    - run: ./taskfile checkLinuxMain
    - run: ./taskfile checkDocs
    - run: ./taskfile test
    - run: ./taskfile codecov

  update_release_draft:
    needs: [test]
    outputs:
      upload_url: ${{ steps.draft_release.outputs.upload_url }}
    runs-on: ubuntu-latest
    steps:
    - id: draft_release
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload_release_artifact:
    needs: [update_release_draft]
    runs-on: macos-10.15
    strategy:
      matrix:
        xcode: 
        - 11.7
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app
    steps:
    - uses: actions/checkout@v2
    - run: ./taskfile selectXcode
    - run: ./taskfile buildReleaseAndZip
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.update_release_draft.outputs.upload_url }}
        asset_path: ./stackgen.zip
        asset_name: stackgen.zip
        asset_content_type: application/zip