name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: macos-10.15
    strategy:
        matrix:
          DEVELOPER_DIR:
          - /Applications/Xcode_11.3.1.app/Contents/Developer
          - /Applications/Xcode_11.4.app/Contents/Developer
    env:
      DEVELOPER_DIR: ${{ matrix.DEVELOPER_DIR }}
    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - uses: actions/cache@v1
      with:
        path: Examples/swift/Carthage
        key: ${{ runner.os }}-${{ env.DEVELOPER_DIR }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}-${{ hashFiles('Examples/swift/Carthage/**') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.DEVELOPER_DIR }}-carthage-
    - uses: actions/cache@v1
      with:
        path: .build
        key: ${{ runner.os }}-${{ env.DEVELOPER_DIR }}-spm-${{ hashFiles('**/Package.resolved') }}-${{ hashFiles('.build/**') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.DEVELOPER_DIR }}-spm-
    - uses: actions/cache@v1
      with:
        path: /private/var/tmp/_bazel_runner
        key: ${{ runner.os }}-${{ env.DEVELOPER_DIR }}-bazel-${{ hashFiles('/private/var/tmp/_bazel_runner/**') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.DEVELOPER_DIR }}-bazel-

    - name: Select Xcode version
      run: sudo xcode-select -s "$DEVELOPER_DIR"

    - name: Setup
      run: sh scripts/setup.sh
    
    - name: Tests
      run: swift test