name: CI
on:
  push:
    branches-ignore:
      - 'master'
  pull_request:
    branches: ['**']

jobs:
  test:
    runs-on: macos-10.15
    name: test - Xcode ${{ matrix.xcode }}
    strategy:
      matrix:
        xcode: 
        - 11.4.1
        - 11.5
        - 11.7
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app
    steps:
    - uses: actions/checkout@v2
    - run: ./taskfile selectXcode
    - run: ./taskfile setup
    - run: ./taskfile checkLinks ${{ github.sha }}
    - run: ./taskfile checkLinuxMain
    - run: ./taskfile checkDocs
    - run: ./taskfile test
    - run: ./taskfile codecov