name: Release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: macos-10.15
    name: Xcode ${{ matrix.xcode }}
    strategy:
      matrix:
        xcode: 
        - 11.5
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app
    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode version
      run: |
        echo "Available Xcode versions:"
        ls /Applications | grep Xcode
        echo "Choosing $DEVELOPER_DIR"
        sudo xcode-select -s "$DEVELOPER_DIR"
        xcodebuild -version
        swift --version
        swift package --version

    - name: Build
      run: |
        swift build -c release
        zip --junk-paths stackgen .build/release/stackgen

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./stackgen.zip
        asset_name: stackgen.zip
        asset_content_type: application/zip